### ISSUE TITLE
about wharf usage?

### ISSUE THREAD

**Issue by moypray** [dockercn/wharf#108]
In wharf wiki, I can see:

Add containerops.com in your hosts file like 192.168.1.66 containerops.me .  
Registry a user at https://containerops.me/auth.   
Login with new user use docker login containerops.com. 
Then push with docker push github.com/somebody/ubuntu. 
You could pull with docker pull -a github.com/somebody/ubuntu.
a github.com/somebody/ubuntu.
Work fun!

Line 1:  Add containerops.me  not comtainerops.com
Line 3: it should be docker login containerops.me. 

So wharf is a tools to manage user database for register Hub,right?? (if not, correct me)
I have run the wharf as the wiki said, and I can see the "register user" page(http://localhost/auth#/), but i can not register new user successfully. Do you know why?

thx

**Comment by genedna** [comment]
All your docker command domain is `containerops.me`

```
docker login containerops.me
docker push containerops.me/somebody/ubuntu # somebody is your username
docker pull -a containerops.me/somebody/ubuntu 
```

**Comment by moypray** [comment]
@genedna  thanks for your reply, I have run it up.

BTW:
About build wharf:
cd /root/gopath/src/github.com
git clone git@github.com:dockercn/wharf.git

should be:
mkdir -p  /root/gopath/src/github.com/dockercn
cd /root/gopath/src/github.com/dockercn
git clone git@github.com:dockercn/wharf.git

or it will build fail too. 
import dockercn/xxx
errno message:   can not find xxx lib.

**Comment by genedna** [comment]
@moypray Thanks, I fix the bug.
