### ISSUE TITLE
where wharf running  on

### ISSUE THREAD

**Issue by HongYuanLi1989** [dockercn/wharf#120]
i  build wharf  on  centos 6.6 (it' a vm by hyperv),not install docker  ,when i Add Repository  the page not response,can you tell me how to fix it ,thank you !

**Comment by HongYuanLi1989** [comment]
i  fix  it   ,  Repository Name  :New unique Repo name; 3 - 30 characters. Only lowercase letters, digits and _ - . characters are allowed  ,but  this  tool  can  create a containers  and start it ?

**Comment by chliang2030598** [comment]
you must push imags before you running it.

**Comment by genedna** [comment]
We will add Docker Remote API support in the feature, then you could start/stop container in the wharf.

**Comment by HongYuanLi1989** [comment]
i find a new problem  ,if i run nginx and wharf on the same host ,443 port  will lock.
i use two host to fix it .
can you tell me how to push the image  ,i do it by the How To Use  but  it does't  work ,
like  this:  docker push --insecure-registry containerops.me/lihongyuan/ubuntu

**Comment by genedna** [comment]
If you run *wharf* behind *Nginx*, you should run `wharf` with *http*.

`conf/bucket.conf`

```conf
enablehttptls = false
```

Run *wharf* with

```bash
sudo ./wharf --port 9911 --address 127.0.0.1
```
