### ISSUE TITLE
管理多个registry

### ISSUE THREAD

**Issue by villl** [dockercn/wharf#64]
能够通过docker-bucket 对多个registry 进行管理。多个registry 之间的的数据保证一致性。若通过docker-bucket push 的过程中，出现个别registry push 失败。则需要进行回滚操作。或通过其他途径实现各个registry 之间的数据一致性。

**Comment by genedna** [comment]
@villl 

1. Docker Bucket 不是 Registry， 可以看做是开源版本的 Docker Hub
2. 你希望是多个 Docker Bucket 在不同数据中心，都保存自己的数据是吧，然后数据和存储的文件之间保证一致性吧？
3. 在使用的过程中，Bucket 是只对自己的数据中心内机器服务，还是可以跨数据中心提供服务？

**Comment by villl** [comment]
希望有一个Docker Bucket 入口。可以管理多个数据中心的registry(及可以跨数据中心提供服务)。

**Comment by genedna** [comment]
那这个模式更像是 Docker Hub 的模式，一个 Docker Hub 和多个 Docker Registry 之间进行服务。对 Docker Bucket 的项目来说，就是设置了 Docker Bucket 的主从模式了。

那属于从地位的几个 Bucket 之间要共享 Image 数据么？

**Comment by genedna** [comment]
这个需求和 #11 是一样的，希望和你讨论需求能更具体一些。

**Comment by genedna** [comment]
duplicate #11

**Comment by villl** [comment]
#11 中的需求感觉是一个docker bucket 对应一个docker registry 。我不了解docker bucket 的主从模式。是类似于mysql 的吗? 要是这样的话。从的docker bucket 之间就无须共享image 了。和住的一直就可以了。

**Comment by genedna** [comment]
#11 是很明确的 Docker Hub 加 Docker Registry 的模式，我们可能会做的稍微不同，但是前提是兼容 Docker 的 API 。

共享还是不共享 Image ，我们可能设定一个配置选项来处理。

**Comment by liuyang430068** [comment]
wharf 现在支持多租户registry吗

**Comment by maquanyi** [comment]
目前不支持，我们准备在下个版本做这个功能。
这个部分会移动到 https://github.com/containerops/dockyard 的工程。
